# Generated by Django 6.0.6 on 2026-07-13 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScanRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_type', models.CharField(choices=[('email', 'Email'), ('url', 'URL'), ('wallet', 'Wallet'), ('website', 'Website')], max_length=20)),
                ('input_data', models.TextField()),
                ('verdict', models.CharField(max_length=50)),
                ('risk_score', models.FloatField()),
                ('confidence', models.FloatField()),
                ('model_used', models.CharField(max_length=100)),
                ('explanation', models.TextField(blank=True)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Threat Scan',
                'verbose_name_plural': 'Threat Scans',
                'ordering': ['-created_at'],
            },
        ),
    ]
