# Generated by Django 6.0.6 on 2026-07-04 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScanRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2048)),
                ('wallet_address', models.CharField(blank=True, max_length=100, null=True)),
                ('ai_risk_score', models.FloatField(help_text="0-100 score from Member A's ML model")),
                ('web3_risk_status', models.CharField(blank=True, max_length=20, null=True)),
                ('web3_reason', models.TextField(blank=True, null=True)),
                ('unified_threat_score', models.FloatField()),
                ('final_verdict', models.CharField(choices=[('SAFE', 'Safe'), ('SUSPICIOUS', 'Suspicious'), ('CRITICAL', 'Critical')], max_length=20)),
                ('gemini_explanation', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
