# Generated by Django 6.0.6 on 2026-07-13 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unified_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanrecord',
            name='explanation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
