# Generated by Django 6.0.6 on 2026-07-07 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unified_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanrecord',
            name='raw_response',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scanrecord',
            name='web3_risk_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='scanrecord',
            index=models.Index(fields=['url'], name='unified_api_url_580a50_idx'),
        ),
        migrations.AddIndex(
            model_name='scanrecord',
            index=models.Index(fields=['final_verdict'], name='unified_api_final_v_637ea5_idx'),
        ),
        migrations.AddIndex(
            model_name='scanrecord',
            index=models.Index(fields=['created_at'], name='unified_api_created_be596b_idx'),
        ),
    ]
